format_version: 10
pipelines:
  pr-test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3e657a9:
        git: https://github.com/loshang/pr-test.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - s1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          j1:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
